import { useEffect, useMemo, useState } from 'react';
import { CheckSquare, Square, Send, Ban, RefreshCw } from 'lucide-react';

const C = { surface: '#0F1117', primary: '#6366F1', text: '#F1F5F9', muted: '#94A3B8', subtle: '#64748B', border: 'rgba(255,255,255,0.08)' };

export default function Broadcasts({ leads, apiFetch, addToast }) {
  const [campaigns, setCampaigns] = useState([]); const [selected, setSelected] = useState([]);
  const [name, setName] = useState(''); const [message, setMessage] = useState(''); const [interval, setInterval] = useState(5);
  const [confirmedOptIn, setConfirmedOptIn] = useState(false); const [saving, setSaving] = useState(false);
  const eligible = useMemo(() => leads.filter(lead => lead.phone), [leads]);
  async function load() { try { setCampaigns(await apiFetch('/broadcasts')); } catch (e) { addToast(`Erro ao carregar disparos: ${e.message}`); } }
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!campaigns.some(c => c.status === 'running')) return undefined; const timer = setInterval(load, 4000); return () => clearInterval(timer); }, [campaigns]);
  function toggle(id) { setSelected(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]); }
  function toggleAll() { setSelected(selected.length === eligible.length ? [] : eligible.map(lead => lead.id)); }
  async function create() {
    if (!name.trim() || !message.trim() || !selected.length || !confirmedOptIn) return; setSaving(true);
    try { const campaign = await apiFetch('/broadcasts', { method: 'POST', body: JSON.stringify({ name, message, leadIds: selected, intervalSeconds: interval, confirmedOptIn }) }); await apiFetch(`/broadcasts/${campaign.id}/start`, { method: 'POST' }); setName(''); setMessage(''); setSelected([]); setConfirmedOptIn(false); addToast('Disparo iniciado com intervalo seguro.'); await load(); } catch (e) { addToast(e.message); } finally { setSaving(false); }
  }
  async function cancel(id) { try { await apiFetch(`/broadcasts/${id}/cancel`, { method: 'POST' }); await load(); addToast('Disparo cancelado.'); } catch (e) { addToast(e.message); } }
  return <div style={{ height: '100%', overflowY: 'auto', padding: 20, color: C.text }}>
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(320px, 1fr) minmax(300px, 1fr)', gap: 18, alignItems: 'start' }}>
      <section style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: 12, padding: 18 }}><h2 style={{ margin: '0 0 5px', fontSize: 17 }}>Novo disparo</h2><p style={{ color: C.subtle, fontSize: 12, margin: '0 0 16px' }}>Envie uma mensagem individual para os contatos selecionados.</p><input className="pulso-input" placeholder="Nome da campanha" value={name} onChange={e => setName(e.target.value)} /><textarea className="pulso-input" rows={5} placeholder="Mensagem... use {nome}, {empresa}" value={message} onChange={e => setMessage(e.target.value)} style={{ marginTop: 9, resize: 'vertical' }} /><label style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 10, fontSize: 12, color: C.muted }}>Intervalo <input type="number" min="3" max="3600" value={interval} onChange={e => setInterval(Math.max(3, Number(e.target.value) || 3))} style={{ width: 60 }} className="pulso-input" /> segundos</label><label style={{ display: 'flex', gap: 8, alignItems: 'flex-start', marginTop: 14, color: C.muted, fontSize: 12, lineHeight: 1.4 }}><input type="checkbox" checked={confirmedOptIn} onChange={e => setConfirmedOptIn(e.target.checked)} /> Confirmo que estes contatos autorizaram receber mensagens.</label><button className="pulso-btn-primary" disabled={saving || !name.trim() || !message.trim() || !selected.length || !confirmedOptIn} onClick={create} style={{ marginTop: 16, padding: '10px 16px', display: 'flex', gap: 7, alignItems: 'center' }}><Send size={14} /> {saving ? 'Criando...' : `Enviar para ${selected.length} contato(s)`}</button></section>
      <section style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: 12, padding: 18 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><h2 style={{ margin: 0, fontSize: 15 }}>Contatos ({eligible.length})</h2><button onClick={toggleAll} style={{ background: 'none', border: 0, color: C.primary, cursor: 'pointer', fontSize: 12 }}>{selected.length === eligible.length ? 'Limpar' : 'Selecionar todos'}</button></div><div style={{ maxHeight: 360, overflowY: 'auto', marginTop: 10 }}>{eligible.map(lead => <button key={lead.id} onClick={() => toggle(lead.id)} style={{ width: '100%', display: 'flex', alignItems: 'center', gap: 9, padding: '9px 5px', color: C.text, background: 'none', border: 0, borderBottom: `1px solid ${C.border}`, textAlign: 'left', cursor: 'pointer' }}>{selected.includes(lead.id) ? <CheckSquare size={15} color={C.primary} /> : <Square size={15} color={C.subtle} />}<span style={{ flex: 1, fontSize: 12 }}>{lead.name}<small style={{ display: 'block', color: C.subtle }}>{lead.phone}</small></span></button>)}{!eligible.length && <p style={{ color: C.subtle, fontSize: 12 }}>Nenhum lead com telefone cadastrado.</p>}</div></section>
    </div>
    <section style={{ marginTop: 18, background: C.surface, border: `1px solid ${C.border}`, borderRadius: 12, padding: 18 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><h2 style={{ margin: 0, fontSize: 15 }}>Histórico de disparos</h2><button onClick={load} style={{ background: 'none', border: 0, color: C.subtle, cursor: 'pointer' }}><RefreshCw size={14} /></button></div><div style={{ marginTop: 12 }}>{campaigns.map(c => <div key={c.id} style={{ display: 'flex', alignItems: 'center', gap: 12, borderBottom: `1px solid ${C.border}`, padding: '9px 0' }}><span style={{ flex: 1, fontSize: 13 }}>{c.name}<small style={{ display: 'block', color: C.subtle }}>{c.sent_count || 0} enviados · {c.failed_count || 0} falhos · {c.total_count} total</small></span><span style={{ color: c.status === 'completed' ? '#22C55E' : c.status === 'running' ? '#F59E0B' : C.muted, fontSize: 11 }}>{c.status}</span>{['running', 'queued', 'paused'].includes(c.status) && <button onClick={() => cancel(c.id)} title="Cancelar" style={{ background: 'none', border: 0, color: '#F43F5E', cursor: 'pointer' }}><Ban size={15} /></button>}</div>)}{!campaigns.length && <p style={{ color: C.subtle, fontSize: 12 }}>Nenhum disparo criado.</p>}</div></section>
  </div>;
}
